# This is a basic workflow to help you get started with Actions

name: Auto PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "features/autoapprove" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull-request:
    name: Open PR to master
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.pull-request.outputs.pr_number }}
    steps:
    - uses: actions/checkout@v3
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      id: pull-request
      with:
        destination_branch: "master"
        pr_title: "create PR to master"
        pr_body: "*An automated PR*"
        pr_label: "automerge"
        github_token: ${{ secrets.MY_PAT }}
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: pull-request
    steps:
    - run: echo ${{ github.actor }}
    - uses: hmarr/auto-approve-action@v2
      with:
        pull-request-number: ${{ needs.pull-request.outputs.pr_number }}
        github-token: ${{ secrets.MY_PAT }}
  auto-merge:
    runs-on: ubuntu-latest
    needs: [pull-request, auto-approve]
    steps:
    - uses: "pascalgn/automerge-action@v0.15.3"
      name: auto-merge
      env:
        PULL_REQUEST: ${{ needs.pull-request.outputs.pr_number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
