# This is a basic workflow to help you get started with Actions

name: Auto PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "features/autoapprove" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: pullRequestNumber
      required: false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull-request:
    name: Open PR to master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "master"
        pr_title: "create PR to master"
        pr_body: "*An automated PR*"
        github_token: ${{ secrets.MY_PAT }}
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
